helmet:
  slot: "helmet"
  type: "armor"
  item-stack:
    material: "paper"
    custom-model-data: 1002
backpack:
  slot: "backpack"
  type: "first-person-backpack"
  height: 1.5
  item-stack:
    material: "paper"
    custom-model-data: 1000
  first-person-item-stack:
    material: "paper"
    custom-model-data: 11000
